<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_options-page',
		'title' => 'options page',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_products',
		'title' => 'Products',
		'fields' => array (
			array (
				'key' => 'field_539c9025d834f',
				'label' => 'Product Images',
				'name' => 'product_images',
				'type' => 'repeater',
				'instructions' => 'Upload multiple images to create a gallery for this product. ',
				'sub_fields' => array (
					array (
						'key' => 'field_539e0da12cd8c',
						'label' => 'Gallery Image',
						'name' => 'gallery_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Image',
			),
			array (
				'key' => 'field_539c77f5b967a',
				'label' => 'Product Description',
				'name' => 'jg_product_description',
				'type' => 'wp_wysiwyg',
				'default_value' => '',
				'teeny' => 0,
				'media_buttons' => 1,
				'dfw' => 1,
			),
			array (
				'key' => 'field_539c8e8fac6cd',
				'label' => 'Product Effects',
				'name' => 'jg_product_effects',
				'type' => 'textarea',
				'instructions' => 'A short description of the product\'s effects.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539c87a65fc74',
				'label' => 'Batch',
				'name' => 'jg_product_batch',
				'type' => 'taxonomy',
				'taxonomy' => 'batch',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_539c88125fc75',
				'label' => 'Strain',
				'name' => 'jg_product_strain',
				'type' => 'taxonomy',
				'taxonomy' => 'strain',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_539c88445fc76',
				'label' => 'Product Type',
				'name' => 'jg_product_type',
				'type' => 'taxonomy',
				'taxonomy' => 'product-type',
				'field_type' => 'checkbox',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_539c886e5fc77',
				'label' => 'Product Usages',
				'name' => 'jg_product_usages',
				'type' => 'taxonomy',
				'taxonomy' => 'usage',
				'field_type' => 'checkbox',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_539c88bd5fc78',
				'label' => 'Product Attributes',
				'name' => 'jg_product_attributes',
				'type' => 'flexible_content',
				'instructions' => 'Add attributes for your products based on the type of product it is. Add additional attributes using the \'additional set\' then choose a label and a value for each new attribute you want to add.',
				'layouts' => array (
					array (
						'label' => 'Concentrate',
						'name' => 'concentrate',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_539c893e5fc7a',
								'label' => 'Distillation Temp',
								'name' => 'distillation_temp',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c89bc5fc7c',
								'label' => 'Decarboxylated',
								'name' => 'decarboxylated',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_539c8a035fc7d',
								'label' => 'Feed Stock',
								'name' => 'feed_stock',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8c635fc7e',
								'label' => 'Extraction Method',
								'name' => 'extraction_method',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8c745fc7f',
								'label' => 'Solvent',
								'name' => 'solvent',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Bud',
						'name' => 'bud',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_539c8ca55fc81',
								'label' => 'Nutrients Used',
								'name' => 'nutrients_used',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8cbc5fc82',
								'label' => 'Growing Media',
								'name' => 'growing_media',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8cc55fc83',
								'label' => 'Flower Time',
								'name' => 'flower_time',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8ccc5fc84',
								'label' => 'Lights Used',
								'name' => 'lights_used',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8ce05fc85',
								'label' => 'Growing Method',
								'name' => 'growing_method',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539c8cee5fc87',
								'label' => 'Flush',
								'name' => 'flush',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Additional Attributes',
						'name' => 'additional',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_539c8d655fc89',
								'label' => 'Additional Attributes',
								'name' => 'additional_attributes',
								'type' => 'repeater',
								'instructions' => 'Add additional attributes here',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_539c8d8c5fc8a',
										'label' => 'Attribute Label',
										'name' => 'label',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539c8dcc5fc8b',
										'label' => 'Attribute Value',
										'name' => 'value',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Attribute',
							),
						),
					),
				),
				'button_label' => 'Add Attribute Set',
			),
			array (
				'key' => 'field_539c8ed4ac6ce',
				'label' => 'Analysis Date',
				'name' => 'jg_analysis_date',
				'type' => 'date_picker',
				'instructions' => 'The analysis date for this product\'s lab test.',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_539c92c920ccd',
				'label' => 'Chemical Composition',
				'name' => 'jg_product_composition',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_539c92d220cce',
						'label' => 'Chemical',
						'name' => 'chemical',
						'type' => 'text',
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_539c92eb20ccf',
						'label' => 'Amount',
						'name' => 'amount',
						'type' => 'number',
						'instructions' => 'The amount of the chemical present, in decimal form',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => 1,
						'step' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Chemical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}
?>