<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_products',
		'title' => 'Products',
		'fields' => array (
			array (
				'key' => 'field_539f839fff99f',
				'label' => 'Product Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539c9025d834f',
				'label' => 'Product Images',
				'name' => 'product_images',
				'type' => 'repeater',
				'instructions' => 'Upload multiple images to create a gallery for this product. ',
				'sub_fields' => array (
					array (
						'key' => 'field_539e0da12cd8c',
						'label' => 'Gallery Image',
						'name' => 'gallery_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Image',
			),
			array (
				'key' => 'field_539c77f5b967a',
				'label' => 'Product Description',
				'name' => 'jg_product_description',
				'type' => 'wp_wysiwyg',
				'default_value' => '',
				'teeny' => 0,
				'media_buttons' => 1,
				'dfw' => 1,
			),
			array (
				'key' => 'field_539c8e8fac6cd',
				'label' => 'Product Effects',
				'name' => 'jg_product_effects',
				'type' => 'textarea',
				'instructions' => 'A short description of the product\'s effects.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539f750e307e7',
				'label' => 'Batches',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539f751f307e8',
				'label' => 'Batch',
				'name' => 'jg_batch',
				'type' => 'repeater',
				'instructions' => 'Create a batch and add batch specific data like analysis date and test results',
				'sub_fields' => array (
					array (
						'key' => 'field_539f755f307e9',
						'label' => 'Analysis Date',
						'name' => 'analysis_date',
						'type' => 'date_picker',
						'column_width' => '',
						'date_format' => 'yymmdd',
						'display_format' => 'dd/mm/yy',
						'first_day' => 1,
					),
					array (
						'key' => 'field_539f757e307ea',
						'label' => 'Test Results',
						'name' => 'test_results',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_539f75a5307eb',
								'label' => 'Chemical',
								'name' => 'chemical',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539f75ae307ec',
								'label' => 'Amount',
								'name' => 'amount',
								'type' => 'number',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => 100,
								'step' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_539f7657307ed',
						'label' => 'Batch Attributes',
						'name' => 'batch_attributes',
						'type' => 'flexible_content',
						'instructions' => 'Add attributes for your products based on the type of product it is. Add additional attributes using the \'additional set\' then choose a label and a value for each new attribute you want to add.',
						'column_width' => '',
						'layouts' => array (
							array (
								'label' => 'Concentrates',
								'name' => 'concentrates',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_539f7684307ee',
										'label' => 'Distillation Temp',
										'name' => 'distillation_temp',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f76a0307ef',
										'label' => 'Decarboxylated',
										'name' => 'decarboxylated',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f76b0307f0',
										'label' => 'Feed Stock',
										'name' => 'feed_stock',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f76b6307f1',
										'label' => 'Extraction Method',
										'name' => 'extraction_method',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f76bc307f2',
										'label' => 'Solvent',
										'name' => 'solvent',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => 'Flower Buds',
								'name' => 'flower_buds',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_539f81feee742',
										'label' => 'Growing Medium',
										'name' => 'growing_medium',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f81feee743',
										'label' => 'Nutrients Used',
										'name' => 'nutrients_used',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f81feee744',
										'label' => 'Flower Time',
										'name' => 'flower_time',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f81feee745',
										'label' => 'Lights Used',
										'name' => 'lights_used',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f81feee746',
										'label' => 'Flush',
										'name' => 'flush',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539f82b2ee747',
										'label' => 'Growing Method',
										'name' => 'growing_method',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
							),
							array (
								'label' => 'Additional Attributes',
								'name' => 'additional',
								'display' => 'row',
								'sub_fields' => array (
									array (
										'key' => 'field_539f8306ee74a',
										'label' => 'Attributes',
										'name' => 'attributes',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_539f830eee74b',
												'label' => 'Label',
												'name' => 'label',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_539f8319ee74c',
												'label' => 'Value',
												'name' => 'value',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => 1,
										'row_limit' => '',
										'layout' => 'table',
										'button_label' => 'Add Attribute',
									),
								),
							),
						),
						'button_label' => 'Add Attributes',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Batch',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_site-options',
		'title' => 'Site Options',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_taxonomy-fields',
		'title' => 'Taxonomy Fields',
		'fields' => array (
			array (
				'key' => 'field_539e15e3826e5',
				'label' => 'Image',
				'name' => 'jg_tax_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'product-type',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'strain',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'usage',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'batch',
					'order_no' => 0,
					'group_no' => 3,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>